spring.application.name=smartservice

spring.datasource.url=jdbc:postgresql://localhost:5432/smartprint
spring.datasource.username=postgres
spring.datasource.password=smartprint
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

graphhopper.osm-file=E:/Projects/SmartPrint/server-app/smartservice/src/main/resources/maps/north-eastern-zone-260508.osm.pbf
graphhopper.graph-folder=E:/Projects/SmartPrint/server-app/smartservice/src/main/resources/mapscache

logging.level.org.springframework.security=DEBUG

app.jwt.expiration-ms=3600000
app.jwt.refresh-expiration-ms=3600000

app.cors.allowed-origins=http://localhost:4200